--liquibase formatted sql

--changeset CREATE_USER_TABLE:DDL_1
CREATE TABLE USER_ACCOUNT(
    ID UUID NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
)

--changeset CREATE_TOKEN_TABLE:DDL_2
CREATE TABLE TOKEN(
    ID UUID NOT NULL PRIMARY KEY,
    TOKEN VARCHAR(150) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRES_IN NUMERIC NOT NULL DEFAULT 10000,
    USER_ACCOUNT_ID UUID NOT NULL,
    CONSTRAINT FK_USER_ACCOUNT_TOKEN FOREIGN KEY(USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID)
)