--liquibase formatted sql

--changeset CREATE_USER_TABLE:DDL_1
CREATE TABLE "USER"(
    ID UUID NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL
)

--changeset CREATE_TOKEN_TABLE:DDL_2
CREATE TABLE TOKEN(
    ID UUID NOT NULL PRIMARY KEY,
    TOKEN VARCHAR(150) NOT NULL,
    CREATED_AT DATE NOT NULL,
    EXPIRES_IN NUMERIC NOT NULL DEFAULT 10000
)